#47
Girls-Do-Code/Girls-Do-Code.github.io pull request #50
Opened 2018-01-18 05:17 UTC by IIT2017032

Issue Number #47 
Changes proposed in this pull request :section for contributors
[Live Link](https://iit2017032.github.io/Girls-who-code/)

2018-01-18 10:23 UTC, ritikamotwani commented
The whole point of my PR was to organize the code and put the css part in a separate file so I don't think it should be added back :)
Further the contributors can be a new section. Contact need not be removed :D

2018-01-18 12:06 UTC, IIT2017032 commented
now i had corrected it

2018-01-18 12:35 UTC, gauthamzz requested changes
This section is too large can you make it smaller. Its just names. Why so much space for it.

2018-01-18 12:35 UTC, gauthamzz commented on index.html
> +<i class="cont2"><b class="name"> Ananya Agrawal
styling is not consistent.

2018-01-19 19:16 UTC, gauthamzz commented
contributers are not at the center in my laptop.

2018-01-20 15:45 UTC, gauthamzz commented
@sangeeta2499 fix the merge conflicts as well. I guess you are good to go.

2018-01-20 18:24 UTC, sangeeta2499 commented
is it correct now?

2018-01-20 18:29 UTC, gauthamzz commented
update your url, you changed your username

2018-01-20 19:06 UTC, sangeeta2499 commented
okk

2018-01-22 03:48 UTC, gauthamzz commented
Idk what you are doing , send me gh pages link of website and finish this by today or I’ll give this to someone else

2018-01-22 03:55 UTC, sangeeta2499 commented
live link( https://sangeeta2499.github.io/Girls-who-code/)

2018-01-22 04:05 UTC, sangeeta2499 commented
live link(https://sangeeta2499.github.io/Girls-who-code/)

2018-01-22 10:15 UTC, gauthamzz commented
See the javascript is overflowing at the bottom of the footer.

2018-01-22 10:16 UTC, gauthamzz requested changes

2018-01-22 10:16 UTC, gauthamzz commented on index.html
> +     <link rel="stylesheet" type="text/css" href="style.css"
The >is not there

2018-01-22 10:16 UTC, gauthamzz commented on index.html
> +     <link rel="stylesheet" type="text/css" href="style.css"
Close the <tag> @sangeeta2499

2018-01-22 13:23 UTC, Sangeetaaa reviewed
closing the tag

2018-01-22 13:33 UTC, Sangeetaaa reviewed
correcting the overflowing of javascript

2018-01-22 13:39 UTC, sangeeta2499 commented
live link(https://sangeeta2499.github.io/Girls-who-code/)

2018-01-22 15:17 UTC, merged