Update events.json
Girls-Do-Code/Girls-Do-Code.github.io pull request #77
Opened 2018-01-25 23:21 UTC by ananya-agrawal

Issue Number #70 
Changes proposed in this pull request : added more events
[Live Link](provide link here)

2018-01-31 15:20 UTC, Anupam-dagar commented
@ananya-agrawal resolve merge conflicts

2018-02-01 13:23 UTC, ananya-agrawal commented
@Anupam-dagar image was added for contribution section.

2018-02-01 14:23 UTC, gauthamzz requested changes
Didn’t I already merge this

2018-02-01 14:23 UTC, gauthamzz commented on static/js/events.json
> +
where is hack in the north
where is opencode 😄

2018-02-01 14:40 UTC, ananya-agrawal commented
@gauthamzz there were two pr containing different events . HINT was added in the earlier one and added opencode in this. Maybe while fixing conflicts two events got repeated so i will verify that after this pr gets merged . Tell if some changes are to be made.

2018-02-01 19:08 UTC, Anupam-dagar commented on static/js/events.json
> +      "title": "Hack-36",
proper indentation needed, everything else LGTM :+1:

2018-02-01 19:09 UTC, Anupam-dagar reviewed
indentation needed

2018-02-01 20:15 UTC, closed without merging