updating readme
Girls-Do-Code/Girls-Do-Code.github.io pull request #90
Opened 2018-02-02 10:01 UTC by ananya-agrawal

Issue Number #84 
Changes proposed in this pull request :
[Live Link](provide link here)

2018-02-02 10:14 UTC, gauthamzz requested changes
Don’t add details of opencode. Other than that this looks good. 

Also add opencode badge to readme.
Add the logo as well to the readme.

2018-02-02 10:14 UTC, gauthamzz commented on README.md
> +# Prizes For Winner of Opencode
Remove this

2018-02-02 10:39 UTC, ananya-agrawal commented
that means should delete everything except Girls who code, our goals, and scoring criterion? @gauthamzz

2018-02-02 12:12 UTC, gauthamzz commented
WHy you need scoring criteria , only add things related to girls who code

2018-02-02 12:25 UTC, ananya-agrawal commented
@gauthamzz pls review

2018-02-06 09:17 UTC, Anupam-dagar reviewed
why is one image added for readme update?

2018-02-07 06:46 UTC, gauthamzz approved these changes

2018-02-07 06:46 UTC, merged